language: python

env:
    global:
        - PACKAGE="NeoVintageous"
        - NO_AT_BRIDGE=1
    matrix:
        - SUBLIME_TEXT_VERSION="3"

matrix:
    include:
        - os: linux
          dist: trusty
          python: 3.3
        - os: linux
          services: xvfb
          python: 3.8
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # Enable GUI. See https://docs.travis-ci.com/user/gui-and-headless-browsers.
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then
                pip install flake8==3.5;
                pip install flake8-docstrings;
                pip install pydocstyle==3.0.0;
                pip install coverage==4.5.4;
                pip install codecov==2.0.15;
                pip install python-coveralls;
                pip install typing==3.7.4.1;
                pip install mypy==0.540;
                flake8 --version;
                mypy --version;
            else
                pip install flake8;
                pip install flake8-docstrings;
                pip install pydocstyle;
                pip install coverage==4.5.4;
                pip install codecov;
                pip install python-coveralls;
                pip install mypy;
                flake8 --version;
                mypy --version;
            fi
      fi
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests --coverage
    - sh travis.sh run_syntax_compatibility
    - sh travis.sh run_syntax_tests
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            flake8;
      fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            wget -v https://github.com/gerardroche/sublime-mypy-stubs/archive/master.zip && unzip master.zip;
            export MYPYPATH="$PWD/sublime-mypy-stubs-master";
            cd "$HOME/.config/sublime-text-3/Packages/$PACKAGE/";
            find . -type d ! -path "*/\.*" ! -path "./tmp*" ! -path "./htmlcov*" ! -path "./bin*" ! -path "./res*" ! -path "./tests/fixtures*" ! -exec test -f "{}/__init__.pyi" ";" ! -exec test -f "{}/__init__.py" ";" -exec touch "{}/__init__.pyi" ";" -print;
            find . -type f -name __init__.py -print && find . -type f -name __init__.pyi -print;
            if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then
                mypy "../$PACKAGE";
            else
                mypy --show-error-codes "../$PACKAGE";
            fi;
      fi
    - cd "$TRAVIS_BUILD_DIR";

after_success:
    - coveralls
    - codecov

notifications:
    email: false
