env:
    global:
        - PACKAGE="NeoVintageous"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

matrix:
    include:
        - os: linux
          language: python
          python: 3.3
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests --coverage

after_success:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew install python3;
            pip3 install python-coveralls;
      fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            pip install python-coveralls;
      fi
    - coveralls

notifications:
    email: false
